language: python
python:
  - "3.2"
  - "3.3"
  - "3.4"
  # does not have headers provided, please ask https://launchpad.net/~pypy/+archive/ppa
  # maintainers to fix their pypy-dev package.
  # here ?
install: "pip3 install -r requirements2.txt"
script: "python3 test_make_GenePS.py test"
